### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by longlongago7** [Algebra-FUN/Unipus-Helper#3]
解压releases里面的压缩包之后，在Chrome浏览器的开发者模式用“加载已解压的拓展程序”的时候添加失败提示：
错误 Cannot load extension with file or directory name _config.yml. Filenames starting with "_" are reserved for use by the system.
无法加载清单。
求大佬指导该怎么办

**Comment by Algebra-FUN** [comment]
不好意思，_config.yml是老版本配置github page的.
您可以直接删除_config.yml或重新下载我新修复的release或直接git pull，已修复该问题.
感谢您对本项目的使用与关注.

**Comment by longlongago7** [comment]
已经按照大佬说的新下载了release的内容，但是这里说有错误
![QQ图片20220526153313](https://user-images.githubusercontent.com/102451445/170440655-67cf1ea3-25b5-4d94-b01d-8bfc1cb97097.png)
![QQ图片20220526153336](https://user-images.githubusercontent.com/102451445/170440727-d41be813-6cb5-48e4-a3a8-b89d27ebb692.png)
而且装上了之后好像没看到插件起了作用（在单元测试）
大佬有效果图可以参考一下嘛

**Comment by Algebra-FUN** [comment]
这不算是error，算是warning，并不影响使用.
而且这个代码有一定年头了，只使用于老版unipus，不同学校使用的unipus版本不同. 如果是U校园这个平台，则是不支持的
且目前功能只有自动填充单元练习内容，不知道你说的单元测试指的那种限时的测试

**Comment by Algebra-FUN** [comment]
这不算是error，算是warning，并不影响使用.
而且这个代码有一定年头了，只使用于老版unipus，不同学校使用的unipus版本不同. 如果是U校园这个平台，则是不支持的
且目前功能只有自动填充单元练习内容，不知道你说的单元测试指的那种限时的测试

**Comment by longlongago7** [comment]
大佬抱歉，前几天github上不去没法回复，我这里的单元测试是不限时的那种，相当于练习题。貌似这个插件也没有按照大佬所说的填充常规单元练习的内容，就像这样，我是还需要设置些什么吗
![QQ图片20220602100204](https://user-images.githubusercontent.com/102451445/171531715-50421e81-63fa-4b72-b704-7163bbcb68f7.png)

**Comment by Algebra-FUN** [comment]
这是U校园，不是传统意义上的Unipus。在疫情前，一般每个学校都用校内网的老unipus；这个U校园是疫情期间，公网版本。不同学校使用的不太一样，反正我们学校还在用老版本……

疫情期间我用过一个叫U校园助手的插件（比本项目诞生的晚），但是作者最近不维护了，可能是用不了了……
https://github.com/Rilomilo/unipus-helper/blob/master/docs/release/unipus_helper_v0.10.0.zip
可以试试这个，估计最近用不了了，因为最早U校园答案都是暴露在html里的，现在应该修复了吧

**Comment by longlongago7** [comment]
谢谢大佬，那我去试试
